### PR TITLE
Removing portal group and updating community props

### PR DESCRIPTION
**Pull request by mrpatrickwest**
Removed dco:PortalGroup, dco:associatedDCOPortalGroup from both .ttl
files. Removed classes from dco-vivo.ttl that aren't in dco.ttl. Added
properties to dco-vivo.ttl that were missing, using the weekly rdf
exports to fill in the blanks.

### CODE REVIEW

**Comment by zednis** [comment]
Looks good to me.  Have these modified files been tested?

**Comment by mrpatrickwest** [comment]
not yet. Still waiting to migrate inOrganization triples to use the position faux property. Once I get that done then I'll test the load.

**Comment by zednis** [comment]
:+1:

**Comment by am-e** [comment]
@mrpatrickwest I've reviewed the changes, all look clean.
:+1:

**Pull request merged**
